### ISSUE TITLE
Duping tasks 

### ISSUE THREAD

**Issue by Tom-y** [seanfrischmann/jira_to_todoist#1]
For some of my tasks its duping the task.

**Comment by seanfrischmann** [comment]
Sorry for the late response, I didn't see this opened!

Hmm, it will recreate the task if your JQL is pulling in that status and you've marked the task in todoist as done. Example: `status in ('In Progress', 'To Do')` will recreate a task after you've marked it done in todoist and the status of the ticket in JIRA is one of the listed.

Alternatively, there could be an issue if you are using a different version of the todoist api version. I just whipped this up and provided practically no documentation :/

Python Version: 2.7.10
todoist-python  7.0.18
